name: "Helm Dependencies"
description: "Keep Helm dependencies updated"
author: Artem Lajko

inputs:
  config-path:
    description: "Path to the dependencies configuration file"
    required: true
  user-email:
    description: "user.email to configure git"
    required: true
  user-name:
    description: "user.name to configure git"
    required: true
  default-branch:
    description: "Repository default branch"
    required: false
    default: "main"
  dry-run:
    description: "Skip creating branch + pull request if set to true"
    required: false
    default: false
  github-run:
    description: "Default set to true. Create branch + pull request"
    required: true
    default: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.config-path }}
    - ${{ inputs.user-email }}
    - ${{ inputs.user-name }}
    - ${{ inputs.default-branch }}
    - ${{ inputs.dry-run }}
    - ${{ inputs.github-run }}
