name: test-helm-dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test-helm-dependencies.yml"
      - "helm-dependencies/**"
      - "examples/dependencies.yaml"

jobs:
  test-helm-dependencies:
    name: "Test: Helm Dependencies Update on Example Chart"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Helm Dependencies
        uses: ./helm-dependencies
        with:
          config-path: examples/dependencies.yaml
          user-email: "dep-sheriff-bot@users.noreply.github.com"
          user-name: "dep-sheriff-bot"
          default-branch: "main"
          dry-run: false
          github-run: true
        env:
          # mandatory: not declared explicitly, but used by gh-cli
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
